
export const CONTRACT_CLAUSES = {
    'Debutante': `1.1 A LOCAÇÃO É FIRMADA MEDIANTE A ENTRADA DE 50% DO VALOR DO SERVIÇO NO QUE SE REFERE A RESERVA, AOS AJUSTES, À LAVAGEM E À ORGANIZAÇÃO DO MESMO. TRATANDO-SE DE CONFECÇÃO DE PRIMEIRO ALUGUEL, O VALOR DE ENTRADA 60% DO VALOR ORÇADO.
1.2 EM CASO DE DESISTÊNCIA OU TROCA DO TRAJE RESERVADO, O VALOR DE ENTRADA NÃO SERÁ ESTORNADO, POIS REFERE-SE A CLÁUSULA 1.1, GERANDO MULTA PELA DESISTÊNCIA, PODENDO SER DESCONTADA NO VALOR DA ENTRADA.
1.3 EM CASO DE MUDANÇA DE DATA DA LOCAÇÃO, O VALOR FICA RETIDO COMO RESERVA PARA PRÓXIMO ALUGUEL COM PRAZO DE LIMITE NO PERÍODO ANUAL VIGENTE.
1.4 QUALQUER ALTERAÇÃO SOLICITADA NO TRAJE E/OU CONFECÇÃO, SERÁ COBRADO VALOR ADICIONAL.
1.5 A PROVA É OBRIGATÓRIA ANTES DA RETIRADA DO TRAJE. DEVE SER MARCADA NO PERÍODO DE FUNCIONAMENTO DO ESTABELECIMENTO. SE O LOCATÁRIO ALEGAR INDISPONIBILIDADE DE HORÁRIO PARA A REALIZAÇÃO DA PROVA, O TRAJE NÃO PODERÁ SER RETIRADO. AJUSTE ADICIONAL SERÁ COBRADO.
1.6 EM CASO DE SOLICITAÇÃO DE ANTECIPAÇÃO DE RETIRADA DO TRAJE SERÁ COBRADO TAXA OU DIÁRIA REFERENTE AO VALOR DO TRAJE. O LOCATÁRIO DEVE INFORMAR NO ATO DA ASSINATURA DO CONTRATO.
1.7 A DEVOLUÇÃO DO TRAJE DEVERÁ SER FEITA NA DATA DEFINIDA PELO ESTABELECIMENTO. O ATRASO IMPLICARÁ NA COBRANÇA DE MULTA POR ATRASO E O VALOR COBRADO PODERÁ SER MULTA POR DIA OU VALOR DE ALUGUEL, DEPENDENDO DA OCORRÊNCIA.
1.8 O TRAJE OS ITENS QUE OS ACOMPANHAM DEVERÃO SER DEVOLVIDOS COM O MESMO ESTADO DE CONSERVAÇÃO QUE FOI ENTREGUE. EM CASO DE DANO, SERÁ COBRADO O VALOR DO DANO E/OU DO ITEM. SE O PRODUTO FOR EXTRAVIADO OU IRREPARÁVEL, SERÁ COBRADO O VALOR TOTAL DO PRODUTO.
1.9 AUTORIZO A EMPIRE TRAJES FINOS FAZER USO DE MINHA IMAGEM EM MATERIAIS DE MARKETING ON LINE E IMPRESSO DA EMPRESA.`,
    'Casamento': `Termos padrão para Casamento (A definir)`,
    'Formatura': `Termos padrão para Formatura (A definir)`,
    'Corporativo': `Termos padrão para Corporativo (A definir)`,
    'Noivado': `Termos padrão para Noivado (A definir)`,
    'Outro': `Termos padrão (A definir)`
};
